@startuml
'https://plantuml.com/class-diagram

class Puzzle
class User
class EloRating
class Problem
class Submission
class Leaderboard
class UserAuth
class Category
class Notifications
class Feedback
class Moderation
class Statistics

Puzzle <--> Problem
User <--> EloRating
User <--> Statistics

@enduml