@startuml
'https://plantuml.com/use-case-diagram
left to right direction
rectangle User{
    :User: as U
}

rectangle CodingPuzzlesApplication{
    (Login) as L
    (Create new Puzzle) as CP
    (Solve Puzzle) as SP
}

U --> L
U --> CP
U --> SP
@enduml