@startuml
'https://plantuml.com/use-case-diagram
left to right direction
rectangle {
    :User: as U
    :Admin: as Admin
}
rectangle CodingPuzzlesApplication{
    (Login) as L
    (Create new Puzzle) as CP
    (Solve Puzzle) as SP
    (Support Creator) as SC
    (Check Puzzle History) as CPH
    (Support Puzzle Creators) as SPC
    (Change Theme) as CT
    (Explore/Learn More) as ELM
    (SSO/User Management) as UM
    (Check Programming News) as PN
}
U --> L
U --> CP
U --> SP
U --> SC
U --> CPH
U --> SPC
U --> CT
U --> ELM
U --> PN
Admin --> UM
@enduml